#!/bin/bash
#Create menu using dialog command

temp=$( mktemp -t test.XXXXXX )
temp2=$( mktemp -t test2.XXXXXX )

diskspace()
{
	df -hk >$temp
	dialog --textbox $temp 20 50
}

whoseon()
{
	who >$temp
	dialog --textbox $temp 20 50
}

memusage()
{
	cat /proc/meminfo >$temp
	dialog --textbox $temp 20 50
}

while [ 0 ]
do
	dialog --menu "System Admin Menu" 20 30 10 1 "Display disk space" 2 "Display users" 3 "Display memory usage" 0 "Exit" 2>$temp2
	if [ $? -eq 1 ]; then
		break
	fi

	option=$( cat $temp2 )
	case $option in
	1)
		diskspace;;
	2)
		whoseon;;
	3)
		memusage;;
	0)
		break;;
	*)
		dialog --msgbox "Invalid selection" 10 30
	esac
done
rm -f $temp 2>/dev/null
rm -f $temp2 2>/dev/null
