#!/bin/bash

list="Alabama Alaska Arizona Arkansas Colorado"
list=$list "elsewhere"
echo $list

list="Alabama Alaska Arizona Arkansas Colorado"
list=$list" elsewhere"
echo $list

for state in $list; do
	echo "Have you ever visited $state?"
done
