#!/bin/bash

addem()
{
	if [ $# -eq 0 ] || [ $# -gt 2 ]; then
		echo -1
	elif [ $# -eq 1 ]; then
		echo $[ $1 + $1 ]
	else
		echo $[ $1 + $2 ]
	fi
}

echo -n "Adding 10 and 5 : "
value=$( addem 10 5 )
echo $value
echo
echo -n "Let's try just one number 10 : "
value=$( addem 10 )
echo $value
